
####################################################################################
# Generated by Vivado 2024.1 built on 'Wed May 22 18:37:14 MDT 2024' by 'xbuild'
# Command Used: write_xdc -force C:/Users/shant/Debounce_and_edge_detection/constrs_1.xdc
####################################################################################


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
